### ISSUE TITLE
Row indexing from top?

### ISSUE THREAD

**Issue by valentinsulzer** [eddierolls/Minesweeper#1]
Currently row indexing starts from the bottom, e.g. (0,0) is here:
```
...
...
X..
```
would be more intuitive to be here
```
X..
...
...
```

**Comment by valentinsulzer** [comment]
Also I think (0,1) should be here
```
.X.
...
...
```
instead of here
```
...
X..
...
```
(as is usually the case with matrix indexing)

**Comment by eddierolls** [comment]
Next on my to do list!

**Comment by eddierolls** [comment]
I was originally working on (x,y) co-ordinates, but agreed this is more sensible

**Comment by eddierolls** [comment]
Done
